---
services:
  - type: web
    name: mashup-creator
    runtime: docker
    region: ohio
    plan: free
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
...
