---
services:
  - type: web
    name: mashup-creator
    runtime: python
    region: ohio
    buildCommand: pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn webapp.app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
...
